version: '3'
services:
  question-answering-chatbot:
    image: question-answering-chatbot:latest
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["python", "main.py"]
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
